spring:
  datasource:
    username: root
    password: yuan199638
    url: jdbc:mysql://localhost:3306/qy?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    #连接池的配置信息
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#  mvc:
#    static-path-pattern: /**
  thymeleaf:
    cache: false
#  mail:
#    host: smtp.163.com
#    username: Y13262639708@163.com
#    password: YUAN199638
#    default-encoding: UTF-8
#  servlet:
#    multipart:
#      max-file-size: 1MB
#      max-request-size: 1024MB

#指定MyBatis配置文件
#mybatis:
#  config-location: classpath:mybatis_config.xml
#  mapper-locations: classpath:mapper/*.xml
#
#server:
#  servlet:
#    context-path: /recitewords

logging:
  level:
    org.springframework.web: info
    com.rich.rich: debug
wechat:
  cp:
    corpId: ww99fb52ea64503670
    addConfigs:
      - agentId: 1000008
        secret: m_EtiGQ8jM1LOWglgLfXjYL8OkoRSV9B7kaCymEMewg
        token: YkJLfo3MslIpBDQb
        aesKey: pkYovEkMX9x4rpTikD7LfGSDd8KbzkwDEU5nyqwxUQf